/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For simplicity implementation
  return false
}

switch (platform) {
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = true
        try {
          nativeBinding = require('./nexus_binding.win32-x64-msvc.node')
        } catch (e) {
          loadError = e
        }
        break
    }
    break
  default:
    // Fallback for verification, normally full loading logic here
    try {
        nativeBinding = require('./nexus_binding.node')
    } catch (e) {
        loadError = e
    }
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { startServer } = nativeBinding

module.exports.startServer = startServer
